version: '3.8'

services:
  ai-firewall:
    build: .
    container_name: ai-firewall
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
